# Generated by Django 5.0.6 on 2024-06-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='authors/default.png', upload_to='authors/'),
        ),
    ]
