# Generated by Django 5.0.6 on 2024-07-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(default='authors/default.png', upload_to='authors/'),
        ),
    ]
