# Generated by Django 5.0.6 on 2024-07-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_bloguser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'get_latest_by': 'id', 'ordering': ['-id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='bloguser',
            name='slug',
            field=models.SlugField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(default='authors/default.png', upload_to='authors/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='sur_name',
            field=models.CharField(max_length=50, verbose_name='Surname'),
        ),
    ]
