# Generated by Django 5.0.6 on 2024-07-10 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bloguser_options_bloguser_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
