# Generated by Django 5.0.6 on 2024-07-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='is_subscribed',
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
    ]
